# Numpy

In [2]:
import numpy as np

In [9]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [10]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [11]:
type(list1)

list

In [12]:
type(arr1)

numpy.ndarray

In [6]:
arr2 = np.arange(10, 20, 2)
arr2

array([10, 12, 14, 16, 18])

In [13]:
list2 = [40, 50, 60]
list2

[40, 50, 60]

In [16]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [17]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [18]:
arr3.shape

(2, 3)

In [19]:
arr4 = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [7, 8, 9], [10, 11, 12] ] ])
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr4.shape

(2, 2, 3)

In [21]:
list1*3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [22]:
arr1*3

array([30, 60, 90])

In [23]:
arr4*3

array([[[ 3,  6,  9],
        [12, 15, 18]],

       [[21, 24, 27],
        [30, 33, 36]]])

In [25]:
arr2 = np.array(list2)
list2

[40, 50, 60]

In [27]:
arr1 * arr2

array([ 400, 1000, 1800])

In [29]:
arr1 * arr4

array([[[ 10,  40,  90],
        [ 40, 100, 180]],

       [[ 70, 160, 270],
        [100, 220, 360]]])

1D (12)
2D (3, 4)
3D (2, 5, 4)

In [34]:
array_task1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
np.array(array_task1).shape

(12,)

In [35]:
array_task2 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
np.array(array_task2).shape

(3, 4)

In [36]:
array_task3 = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]], 
               [[21, 22, 23, 24], [25, 26, 27, 28], [29, 30 ,31, 32], [33, 34, 35, 36], [37, 38, 39, 40]]]
np.array(array_task3).shape

(2, 5, 4)

In [37]:
arr3[1][2]

60

In [39]:
arr3[:, 2]

array([30, 60])

In [40]:
arr3[1, :]

array([40, 50, 60])

In [41]:
arr3.sum()

210

In [42]:
arr3.sum(0)

array([50, 70, 90])

In [43]:
arr3.sum(1)

array([ 60, 150])

In [46]:
for x in arr3:
    for num in x:
        print(num)

10
20
30
40
50
60


In [47]:
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60
